#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $(basename $0) file"
    exit 1
fi

for filename in "$@"; do
    bakfile="$filename.bak"
    if [ -e "$bakfile" ]; then
        echo "$bakfile already exists"
        read -p "Overwrite file? [y/N] " response
        response=${response:0:1}
        if [ "$response" == "n" ] || [ "$response" == "N" ]; then
            exit 2
        fi
    fi
    cp $filename $bakfile
done
