#!/bin/bash

usage="Usage: $(basename $0) PDB_file atom_selection"
if [ -z "$1" ]; then
    echo $usage
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Error: No such file: $1"
    exit 2
fi

# idk why vim complains about the ":", it's a valid slice
args=($@)
filename=${args[0]}
sel=${args[@]:1}

vmd -dispdev none -e $HOME/src/vmd/calc_com.tcl -args "$filename" "$sel" | grep -E "^[-0-9.]+ +[-0-9.]+ +[-0-9.]+"
