#!/usr/bin/env python3
# checks a file for whole lines that are duplicated
from sys import argv, exit, stdin

if len(argv) == 1:
    infile = stdin
else:
    infile = open(argv[1])

try:
    unique = set()
    with infile:
        for line in infile:
            line = line.strip()
            if line in unique:
                print("Duplicate:", line)
            else:
                unique.add(line)
except (EOFError, KeyboardInterrupt) as exc:
    print()
    exit()
