#!/usr/bin/env python3
import argparse
from PIL import Image, ImageColor

helpmsg = "Concatenate images along a specified dimension. "
parser = argparse.ArgumentParser(description=helpmsg)
parser.add_argument('--color', '-c', type=ImageColor.getrgb,
        default=[255]*3, help="color to make alpha")
parser.add_argument('filename', nargs='+', help="Images to concatenate")

args = parser.parse_args()

import numpy as np
import os

color3 = np.array(args.color, dtype=np.uint8)
white = np.uint8(255)
for filename in args.filename:
    im = Image.open(filename)
    im = im.convert(mode='RGB')
    pixels = np.asarray(im)

    alpha = (pixels == color3)
    alpha = (alpha.all(axis=2) == False) * white
    alpha = Image.fromarray(alpha, mode="L")
    im.putalpha(alpha)

    basename = os.path.splitext(filename)[0]
    outname = basename + '_alpha.png'
    im.save(outname)
