#!/bin/bash

if [ -z "$1" ]; then
    echo "Define what?"
    exit 1
fi


# get a URL-safe version of the user's query
pystr="from urllib.parse import quote; print(quote('$@'))"
q=$(python3 -c "$pystr")

echo $q

open http://www.thefreedictionary.com/$q
