#!/bin/bash

if [ -z "$1" ]; then
    echo "Define what?"
    exit 1
fi


# get a URL-safe version of the user's query
pystr="from urllib import quote; print quote('$@')"
q=$(python -c "$pystr")

open http://www.thefreedictionary.com/$q
