#!/bin/bash
# A program to open up a program from ~/bin for editing in vim
# File must already exist

prog="$HOME/bin/$1"

echo "Attempting to edit $prog ..."
if [ -e "$prog" ]; then
    vim $prog
    exit 0
fi

echo "Cannot edit $prog: file does not exist"
exit 1
