#!/bin/bash
# Recursively searches files in a directory, looking only at files matching
# a given filename pattern

usage="Usage: $(basename $0) dir filter regexp"

if [ -z "$1" ]; then
    echo "Error: missing base directory"
    echo $usage
    exit 1
fi
if [ -z "$2" ]; then
    echo "Error: missing filename filter"
    echo $usage
    exit 2
fi
if [ -z "$3" ]; then
    echo "Error: missing regular expression"
    echo $usage
    exit 3
fi

base="$1"
filter="$2"
regexp="$3"

find "$base" -name "$filter" | while read filename; do
    # skip directories, and show line numbers
    results="$(grep -n -d skip -E "$regexp" $filename)"
    if [ -n "$results" ]; then
        echo "$filename: $results"
    fi
done
