#!/usr/bin/env python3
from networkx.utils import open_file
import pickle
import sys

@open_file(0, mode='rb')
def read_gpickle(path):
    return pickle.load(path)

G = read_gpickle(sys.argv[1])

import code, readline, rlcompleter
readline.parse_and_bind('tab: complete')
code.InteractiveConsole(locals()).interact()
