#!/usr/bin/env python3
from PIL import Image
import numpy as np
import sys

im = Image.open(sys.argv[1])
arr = np.asarray(im)

import code, readline, rlcompleter
readline.parse_and_bind('tab: complete')
code.InteractiveConsole(locals()).interact()
