#!/bin/bash
# Usage: lsbin [globbing_pattern]
# without arguments, shows the whole contents of ~/bin. With an argument,
# displays only the files that contain "globbing_pattern" somewhere in
# their filename

cd $HOME/bin

if [ -n "$1" ]; then
    ls *$1*
else
    ls
fi
