#!/bin/bash
# Can be used only from the current directory
# Opens however many terminals are specified

if [ $# -eq 0 ]; then
    echo "Usage: $0 integer"
    exit 1
fi

for i in `seq $1`; do
    term
done
