#!/usr/bin/env python
# Returns the smallest float that occurs in the given file
# File should contain only valid floats and white space
from sys import argv

infile = argv[1]

import numpy as np
numbers = np.loadtxt(infile)

print(numbers.min())
