#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $(basename $0) file"
    echo "file should be either a PSF or PDB file"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Error: No such file: $1"
    echo "Usage: $(basename $0) file"
    echo "file should be either a PSF or PDB file"
    exit 2
fi

tmpfile=$(mktemp tmp.XX)
[ $? -eq 0 ] || exit $? # exit on failure to create temporary file

grep -Eo "\-?[0-9]+\.[0-9]+ +-?[0-9]+\.[0-9]+ +-?[0-9]+\.[0-9]+" $1 >> $tmpfile

python << END
import numpy as np
import matplotlib.pyplot as plt

data = np.loadtxt("$tmpfile")
figure, axes = plt.subplots(1, 3)
fig_xlabels = ["X", "Y", "Z"]
fig_ylabel  = "Count"
for index, column in enumerate(data.T):
    bins, edges = np.histogram(column)
    delta = edges[1] - edges[0]
    edges = map(lambda x: x + delta, edges[:-1])

    xlabel = fig_xlabels[index]
    rng="{} range: {:.4f} - {:.4f}".format(xlabel,column.min(),column.max())
    print rng

    axes[index].bar(edges, bins, delta * 0.9)
    axes[index].set_xlabel(xlabel)

axes[0].set_ylabel(fig_ylabel)
plt.show()
END

rm -f $tmpfile
