#!/usr/bin/env python3
import sys

files = []
for fn in sys.argv[1:]:
    with open(fn) as fh:
        contents = fh.read()
    files.append(contents)

import code, readline, rlcompleter
readline.parse_and_bind('tab: complete')
code.InteractiveConsole(locals()).interact()
