#!/usr/bin/env python3
import os
import sys
from os.path import join as pjoin
from cli_utils import get_input

if len(sys.argv) == 1:
    dirs = '.',
else:
    dirs = sys.argv[1:]

confirm = dirs[0].lower() == '-y'

for root in dirs:
    for dirpath, dirnames, filenames in os.walk(root):
        if '.DS_Store' in filenames:
            path = pjoin(dirpath, '.DS_Store')
            prompt = "Remove {}? [y/N] ".format(path)
            if confirm:
                remove = get_input(prompt, allowed="ynYN",
                        default="n").lower()
            if not confirm or remove == "y":
                os.unlink(path)
