#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Error: $0: Must have exactly two args"
    exit 1
fi

tmpfile=$(mktemp)

cp $1 $tmpfile
cp $2 $1
cp $tmpfile $2
rm $tmpfile  # not sure it is really necessary to do it this way
