#!/usr/bin/env python2
from sys import argv, stdin

if len(argv) > 1:
    print " ".join(map(lambda s: s.upper(), argv[1:]))
else:
    with stdin:
        for line in stdin:
            print line.upper(),
