#!/bin/bash

if [ -z "$1" ]; then
    echo Which patch?
fi

pres=$(toupper $1)

cd $TOPPAR
fn=$(grep -rl "PRES $pres" .)

if [ $? -ne 0 ]; then
    echo "Couldn't find patch: $pres"
    exit 1
fi

echo $fn
vim "+/PRES $pres" "+echo v:argv" $fn
