#!/bin/bash

if [ -z "$1" ]; then
    progname=$(basename $0)
    echo "Usage: $progname header_file"
    echo -e "\tSearches for a given header file in /usr/include, opening it"
    echo -e "\twith vim -R if it exists"

    exit 1
fi

header_name=/usr/include/$1

if [ -e "$header_name" ]; then
    vim -R $header_name
else
    echo "Error: $header_name does not exist"
    exit 2
fi
