#!/bin/bash

# set a standard location to write clipboard contents in AIFF
tmpfile=/tmp/clipboard.aiff

# write clipboard contents to $tmpfile's location
if [[ "$1" == "-" ]]; then
    args=$@
    args[0]=""
    set -e
    cat - | prepsay | say ${args[@]} -o $tmpfile
else
    set -e
    saycpy $@ -o $tmpfile
fi

# open the file in VLC
open -a VLC $tmpfile

# in a disconnected subshell, wait 1 minute, then unlink $tmpfile; return immediately
(sleep 60 && rm $tmpfile) &
