#!/usr/bin/env python3
import sys
import yaml

def load_yaml(filename):
    with open(filename) as fh:
        return yaml.load(fh, Loader=yaml.FullLoader)

def dump_yaml(data, filename):
    with open(filename, 'w') as fh:
        yaml.dump(data, filename)

num = 0
for num, arg in enumerate(sys.argv[1:]):
    obj = load_yaml(arg)

    num += 1
    globals().update({f'obj{num}': obj})

if num == 1:
    print(obj)
else:
    print()
    print('variables:', ', '.join([_d for _d in dir() if 'obj' in _d]))
    print()

import code, readline, rlcompleter
readline.parse_and_bind('tab: complete')
code.InteractiveConsole(locals()).interact()
